server:
  # Usa la variable de entorno $PORT. Si no existe dicha variable usa el puerto 8080
  port: ${PORT:8080}
spring:
  datasource:
    url: ${PROFACE_DATABASE_URL}
    username: ${PROFACE_DATABASE_USERNAME}
    password: ${PROFACE_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  signing-key: ${PROFACE_SIGNING_KEY}
  security-realm: ${PROFACE_SECURITY_REALM}
  oauth2:
    resource:
      filter-order: 3
  jwt:
    client-id: ${PROFACE_CLIENT_ID}
    client-secret: ${PROFACE_CLIENT_SECRET}
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: ${PROFACE_RESOURCE_IDS}
        
        