server:
  # Usa la variable de entorno $PORT. Si no existe dicha variable usa el puerto 8080
  port: ${PORT:8080}
spring:
  application:
    name: proface.api
  data:
    rest:
      basePath: /api
  datasource:
    # jdbc:mysql://localhost:3306/proface?serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: ${PROFACE_DATABASE_URL}
    username: ${PROFACE_DATABASE_USERNAME}
    password: ${PROFACE_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
security:
  signing-key: ${PROFACE_SIGNING_KEY}
  security-realm: ${PROFACE_SECURITY_REALM}
  oauth2:
    resource:
      filter-order: 3
  jwt:
    client-id: ${PROFACE_CLIENT_ID}
    client-secret: ${PROFACE_CLIENT_SECRET}
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: ${PROFACE_RESOURCE_IDS}
logging:
  file: logs/ProfaceLog.log
  level:
    root: INFO
    com:
      proface:
        api: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %p[%t] %c{0}.%M : %m%n%ex"
    file: "%d{yyyy-MM-dd HH:mm:ss} %p[%t] %c{0}.%M : %m%n%ex"